name: Render & Deploy Quarto Website (Scheduled)

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab
  schedule:
    # Runs every day at 00:00 UTC (02:00 SAST)
    # Learn more about cron syntax: https://crontab.guru/
    - cron: '0 0 * * *'

  push: # Trigger on push to main branch
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    # Grant GITHUB_TOKEN permissions to deploy to GitHub Pages
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use any Python 3 version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Quarto
        uses: quarto-dev/quarto-action@v2
        with:
          version: 1.4.550 # Explicitly set a stable Quarto version
          # pin-github-pages-version: true # Keep commented unless specifically needed

      - name: Render Quarto project
        run: quarto render

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs' # The folder Quarto outputs to

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4